services:
  # RCS Authentication Web Service
  - type: web
    name: rcs-auth-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /health
    numInstances: 1
    autoDeploy: true
    envVars:
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      
      # Application URL (will be updated after deployment)
      - key: APP_URL
        value: https://rcs-auth-service.onrender.com
      
      # Authentication Settings
      - key: SESSION_DURATION_DAYS
        value: "7"
      - key: RCS_SECURITY_REQUIRED
        value: "true"
      - key: ALLOW_SMS_INITIAL_CONTACT
        value: "true"
      
      # RCS Setup URL
      - key: RCS_SETUP_URL
        value: https://rcs-auth-service.onrender.com/rcs-setup
      
      # The following must be set in Render Dashboard:
      # - SUPABASE_URL
      # - SUPABASE_ANON_KEY
      # - SUPABASE_SERVICE_ROLE_KEY
      # - TWILIO_ACCOUNT_SID
      # - TWILIO_AUTH_TOKEN
      # - TWILIO_PHONE_NUMBER
      # - MESSAGING_SERVICE_SID
      # - RCS_SENDER_ID (optional until RCS is approved)